compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - x64
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-4.1.0.cjs
